RegisterCommand("psary", function ()
    print("test client command")
    TriggerEvent("atom-web:board")
end, false)

RegisterNetEvent("atom-web:show-board")
AddEventHandler("atom-web:show-board", function(data)
    print("test client command2")
    SetNuiFocus(false,false)
	SendNUIMessage(data)
end)